# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_of_VA2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import sys
import assistant_details
from input_module import *
import os
os.add_dll_directory(r'C:\Program Files\VideoLAN\VLC')
import vlc

os.system("CLS")
i=""
o=""


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 652)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(-10, 480, 471, 81))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.button2.setFont(font)
        self.button2.setAutoFillBackground(False)
        self.button2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button2.setAutoDefault(False)
        self.button2.setDefault(False)
        self.button2.setFlat(False)
        self.button2.setObjectName("button2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(-30, 0, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label1.setFont(font)
        self.label1.setAutoFillBackground(False)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setScaledContents(False)
        self.label1.setObjectName("label1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("jpg2png/VA2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.button3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_2.setGeometry(QtCore.QRect(-10, 550, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(14)
        self.button3_2.setFont(font)
        self.button3_2.setAutoFillBackground(False)
        self.button3_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.button3_2.setObjectName("button3_2")
        self.label.raise_()
        self.label1.raise_()
        self.button2.raise_()
        self.button3_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 22))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        self.menuEDIT = QtWidgets.QMenu(self.menubar)
        self.menuEDIT.setObjectName("menuEDIT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFILE.menuAction())
        self.menubar.addAction(self.menuEDIT.menuAction())

        self.wishing()
        self.button3_2.clicked.connect(self.wishing)
        
        self.button2.clicked.connect(self.taking_input)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button2.setText(_translate("MainWindow", "user input"))
        self.label1.setText(_translate("MainWindow", "              F.R.I.D.A.Y"))
        self.button3_2.setText(_translate("MainWindow", "wish me!"))
        self.menuFILE.setTitle(_translate("MainWindow", "FILE"))
        self.menuEDIT.setTitle(_translate("MainWindow", "EDIT"))     

    def wishing(self):
        from welcome import greet
        from output_module import give_output
        g = greet()
        give_output(g)

    def taking_input(self):
        #from input_module import take_input,App
        from process_module import process
        from output_module import give_output 
        from database import speak_is_on
        i = take_input(self)   
        o = process(self,i)
        give_output(o)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
